kind: Pipeline
apiVersion: tekton.dev/v1
metadata:
  name: bats-integration
spec:
  description: |
    Test the newly-built ramalama image and layered images on all supported architectures.
  params:
  - name: SNAPSHOT
    description: >-
      Information about the components included in the current snapshot under test.
  - name: git-url
    description: URL of the Git repository containing pipeline and task definitions
    default: https://github.com/containers/ramalama
  - name: git-revision
    description: Revision of the Git repository containing pipeline and task definitions
    default: main
  tasks:
  - name: init
    params:
    - name: SNAPSHOT
      value: $(params.SNAPSHOT)
    taskSpec:
      params:
      - name: SNAPSHOT
      results:
      - name: TEST_OUTPUT
        description: Task result in json format
      - name: bats-image
        description: URI of the bats image included in the snapshot
      - name: ramalama-image
        description: URI of the ramalama image included in the snapshot
      steps:
      - name: process
        image: registry.access.redhat.com/ubi10/ubi:latest
        env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: RESULTS_TEST_OUTPUT_PATH
          value: $(results.TEST_OUTPUT.path)
        - name: RESULTS_BATS_IMAGE_PATH
          value: $(results.bats-image.path)
        - name: RESULTS_RAMALAMA_IMAGE_PATH
          value: $(results.ramalama-image.path)
        script: |
          #!/bin/bash -ex
          dnf -y install jq
          jq -j '.components[] | select(.name == "bats") | .containerImage' <<< "$SNAPSHOT" | tee $RESULTS_BATS_IMAGE_PATH
          jq -j '.components[] | select(.name == "ramalama") | .containerImage' <<< "$SNAPSHOT" | tee $RESULTS_RAMALAMA_IMAGE_PATH
          jq -jnc '{result: "SUCCESS", timestamp: now | todateiso8601, failures: 0, successes: 2, warnings: 0}' | tee $RESULTS_TEST_OUTPUT_PATH
  - name: test
    matrix:
      params:
      - name: PLATFORM
        value:
        - linux-c4xlarge/amd64
        - linux-c4xlarge/arm64
    params:
    - name: image
      value: $(tasks.init.results.bats-image)
    - name: git-url
      value: $(params.git-url)
    - name: git-revision
      value: $(params.git-revision)
    - name: cmd
      value: make bats
    - name: envs
      value:
      - RAMALAMA_IMAGE=$(task.init.results.ramalama-image)
    taskRef:
      resolver: git
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
      - name: pathInRepo
        value: .tekton/integration/tasks/test-vm-cmd.yaml
